#! /bin/bash
echo -n "Running charmm just to check the input files"
/home/javidi/charmm/charmm.beta.good/exec/gnu/charmm.medium.beta.cvel.one iseed=43245 temp=300 <ch1_2bead.inp >ch1_2bead.out
printf "\n"
